### PR TITLE
Fix `parent` type of `Visitor`

### LINKED ISSUE #17: [Types]: type of parent should be Parent
Hi, currently the type for Visitor is 

```
  type Visitor<V extends Node> = (
    node: V,
    index: number,
    parent: Node
  ) => void | Action | Index | ActionTuple
```

I think the parent parameter should be of type `Parent`, as the type `Node` does not have a children property.

### PR DESCRIPTION
**Pull request by Murderlon**
Fixes #17

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ declare namespace visit {
   type Visitor<V extends Node> = (
     node: V,
     index: number,
-    parent: Node
+    parent: Parent
```
Comment (ChristianMurphy) [inline types/index.d.ts:41]: Root elements have no `parent`, in that case this value would be `undefined`
```suggestion
    parent: Parent | undefined
```

**Comment by wooorm** [comment]
Sweet, thanks, released!
